-- BU BETİK ÇALIŞTIRILDIĞINDA MEVCUT TABLOLARI VE VERİLERİ SİLER, SONRA YENİDEN OLUŞTURUR.

-- Bağımlılıklar nedeniyle tabloları ters sırada sil
DROP TABLE IF EXISTS public.order_items;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.cart_items;
DROP TABLE IF EXISTS public.user_addresses;
DROP TABLE IF EXISTS public.profiles;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.categories;
DROP FUNCTION IF EXISTS public.upsert_cart_item;
DROP FUNCTION IF EXISTS public.handle_new_user;

-- 1. KATEGORİLER TABLOSU
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ÜRÜNLER TABLOSU
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL CHECK (price > 0),
  original_price NUMERIC CHECK (original_price >= price),
  image TEXT,
  stock INT DEFAULT 0 CHECK (stock >= 0),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  colors TEXT[],
  sizes TEXT[],
  is_new BOOLEAN DEFAULT FALSE,
  is_best_seller BOOLEAN DEFAULT FALSE,
  discount INT CHECK (discount >= 0 AND discount <= 100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PROFİLLER TABLOSU (E-POSTA SÜTUNU EKLENDİ)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  birth_date DATE,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- YENİ KULLANICI İÇİN OTOMATİK PROFİL OLUŞTURMA FONKSİYONU
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- YENİ KULLANICI KAYDOLDUĞUNDA FONKSİYONU ÇALIŞTIRAN TETİKLEYİCİ
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- GÜVENLİK KURALLARI (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public read access to categories" ON public.categories FOR SELECT USING (true);


-- 4. SEPET TABLOSU
CREATE TABLE public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INT NOT NULL CHECK (quantity > 0),
  size TEXT NOT NULL,
  color TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT user_product_size_color_unique UNIQUE (user_id, product_id, size, color)
);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own cart items." ON public.cart_items FOR SELECT USING ( auth.uid() = user_id );
CREATE POLICY "Users can insert into their own cart." ON public.cart_items FOR INSERT WITH CHECK ( auth.uid() = user_id );
CREATE POLICY "Users can update their own cart items." ON public.cart_items FOR UPDATE USING ( auth.uid() = user_id );
CREATE POLICY "Users can delete from their own cart." ON public.cart_items FOR DELETE USING ( auth.uid() = user_id );

-- 5. KULLANICI ADRESLERİ TABLOSU
CREATE TABLE public.user_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT, -- Ev, İş gibi adres başlığı
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT, -- Apt, Kat, Daire No gibi
  city TEXT NOT NULL,
  state TEXT, -- İlçe veya eyalet
  zip_code TEXT, -- Posta kodu
  country TEXT NOT NULL DEFAULT 'Türkiye',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  -- Bir kullanıcının sadece bir varsayılan adresi olabilir
  UNIQUE (user_id, is_default) WHERE is_default IS TRUE
);
ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own addresses." ON public.user_addresses FOR SELECT USING ( auth.uid() = user_id );
CREATE POLICY "Users can insert their own addresses." ON public.user_addresses FOR INSERT WITH CHECK ( auth.uid() = user_id );
CREATE POLICY "Users can update their own addresses." ON public.user_addresses FOR UPDATE USING ( auth.uid() = user_id );
CREATE POLICY "Users can delete their own addresses." ON public.user_addresses FOR DELETE USING ( auth.uid() = user_id );

-- 6. SİPARİŞLER TABLOSU (ÖDEME BİLGİLERİ EKLENDİ)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  total_price NUMERIC NOT NULL CHECK (total_price >= 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'paid', 'failed', 'chargeback')), -- Ödeme statusleri eklendi
  payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'paid', 'failed', 'refunded', 'partial_refund', 'chargeback', 'pending_payment')), -- PayTR'dan gelecek ödeme durumu
  payment_id TEXT, -- PayTR işlem ID'si
  payment_type TEXT, -- Ödeme tipi (kart, havale vb.)
  installment TEXT, -- Taksit sayısı
  paytr_error_code TEXT, -- PayTR'dan gelen hata kodu
  paytr_error_message TEXT, -- PayTR'dan gelen hata mesajı
  shipping_address JSONB, -- Adres ID'si veya adresin snapshot'ı
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. SİPARİŞ KALEMLERİ TABLOSU
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  price_at_purchase NUMERIC NOT NULL
);

-- 8. SEPET GÜNCELLEME FONKSİYONU (Artık kullanılmıyor ama şemada kalabilir)
CREATE OR REPLACE FUNCTION public.upsert_cart_item(
  p_user_id UUID,
  p_product_id BIGINT,
  p_size TEXT,
  p_color TEXT,
  p_quantity_change INT
)
RETURNS VOID AS $$
BEGIN
  INSERT INTO public.cart_items (user_id, product_id, size, color, quantity)
  VALUES (p_user_id, p_product_id, p_size, p_color, p_quantity_change)
  ON CONFLICT ON CONSTRAINT user_product_size_color_unique
  DO UPDATE SET quantity = cart_items.quantity + p_quantity_change;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 9. ÖRNEK VERİ EKLEME
INSERT INTO categories (name) VALUES ('Bra'), ('Panty'), ('Sets'), ('Nightwear');

INSERT INTO products (name, description, price, original_price, image, stock, category_id, colors, sizes, is_new, is_best_seller, discount) VALUES
('Classic Comfort Bra', 'Our most comfortable everyday bra.', 450.00, 500.00, 'https://placehold.co/600x400/232323/FFF?text=Bra1', 100, (SELECT id FROM categories WHERE name = 'Bra'), '{"black", "nude", "white"}', '{"XS", "S", "M", "L", "XL"}', TRUE, FALSE, 10),
('Lace Trim Panty', 'Delicate lace trim panty for everyday luxury.', 250.00, NULL, 'https://placehold.co/600x400/555555/FFF?text=Panty1', 150, (SELECT id FROM categories WHERE name = 'Panty'), '{"red", "black"}', '{"S", "M", "L"}', FALSE, TRUE, NULL),
('Silk Nightdress', 'Luxurious silk nightdress for a peaceful sleep.', 900.00, 1200.00, 'https://placehold.co/600x400/777777/FFF?text=Nightwear1', 50, (SELECT id FROM categories WHERE name = 'Nightwear'), '{"champagne", "black"}', '{"S", "M", "L", "XL"}', TRUE, TRUE, 25),
('Matching Lingerie Set', 'Elegant bra and panty set.', 700.00, 850.00, 'https://placehold.co/600x400/999999/FFF?text=Set1', 75, (SELECT id FROM categories WHERE name = 'Sets'), '{"purple", "black"}', '{"S", "M"}', FALSE, FALSE, 15);
