import { Product, Campaign } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Elegant Lace Bra',
    price: 49.99,
    originalPrice: 69.99,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=600&fit=crop',
      'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=500&h=600&fit=crop',
    ],
    category: 'bra',
    colors: ['Black', 'White', 'Red'],
    sizes: ['32A', '32B', '34A', '34B', '36B'],
    description: 'Luxurious lace bra with delicate floral patterns and comfortable underwire support.',
    material: '85% Polyamide, 15% Elastane',
    careInstructions: 'Hand wash cold, lay flat to dry',
    inStock: true,
    isNew: true,
    discount: 30,
  },
  {
    id: '2',
    name: 'Silk Comfort Panty',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1564859228273-274232fdb516?w=500&h=600&fit=crop',
    category: 'panty',
    colors: ['Black', 'Nude', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Ultra-soft silk panty for all-day comfort.',
    material: '95% Silk, 5% Elastane',
    careInstructions: 'Machine wash cold, gentle cycle',
    inStock: true,
    isBestSeller: true,
  },
  {
    id: '3',
    name: 'Romantic Lingerie Set',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=500&h=600&fit=crop',
    category: 'sets',
    colors: ['Red', 'Black', 'White'],
    sizes: ['S', 'M', 'L'],
    description: 'Complete lingerie set with matching bra and panty.',
    material: '90% Polyester, 10% Spandex',
    careInstructions: 'Hand wash recommended',
    inStock: true,
    isNew: true,
    discount: 25,
  },
  {
    id: '4',
    name: 'Satin Nightgown',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=500&h=600&fit=crop',
    category: 'nightwear',
    colors: ['Purple', 'Black', 'Champagne'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Elegant satin nightgown with lace trim details.',
    material: '100% Satin Polyester',
    careInstructions: 'Machine wash cold, hang to dry',
    inStock: true,
  },
  {
    id: '5',
    name: 'Push-Up Wonder Bra',
    price: 54.99,
    image: 'https://images.unsplash.com/photo-1586796676792-f1c2e7c1d1cc?w=500&h=600&fit=crop',
    category: 'bra',
    colors: ['Black', 'Beige'],
    sizes: ['32B', '34B', '36B', '38B'],
    description: 'Maximum lift and support with comfortable padding.',
    material: '80% Nylon, 20% Spandex',
    careInstructions: 'Hand wash cold',
    inStock: true,
    isBestSeller: true,
  },
  {
    id: '6',
    name: 'Cotton Comfort Brief',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1560343776-97e7d202ff0e?w=500&h=600&fit=crop',
    category: 'panty',
    colors: ['White', 'Black', 'Gray', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'Everyday comfort with breathable cotton fabric.',
    material: '95% Cotton, 5% Elastane',
    careInstructions: 'Machine wash warm',
    inStock: true,
  },
]

export const campaigns: Campaign[] = [
  {
    id: '1',
    title: 'Yeni Gelenler',
    description: 'En yeni koleksiyonumuzu keşfedin',
    image: 'https://images.unsplash.com/photo-1594633313515-7ad9334a2349?w=800&h=400&fit=crop',
    link: '/products?filter=new',
    badge: 'YENİ',
  },
  {
    id: '2',
    title: 'Yaz İndirimi',
    description: 'Seçili ürünlerde %50\'ye varan indirim',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=400&fit=crop',
    link: '/products?filter=sale',
    badge: '-%50',
  },
  {
    id: '3',
    title: 'Çok Satanlar',
    description: 'En çok sevilen parçalarımızı keşfedin',
    image: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=800&h=400&fit=crop',
    link: '/products?filter=bestseller',
    badge: 'POPÜLER',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Ayşe Yılmaz',
    rating: 5,
    comment: 'Harika kalite ve mükemmel kalıp! Kesinlikle tekrar sipariş vereceğim.',
  },
  {
    id: '2',
    name: 'Zeynep Demir',
    rating: 5,
    comment: 'Şimdiye kadar giydiğim en rahat iç çamaşırı. Çok beğendim!',
  },
  {
    id: '3',
    name: 'Elif Kaya',
    rating: 5,
    comment: 'Harika tasarımlar ve mükemmel müşteri hizmeti.',
  },
]
